# Generated by Django 4.0 on 2022-02-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjaKsiazkowa2', '0003_auto_20211013_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='data publikacji'),
        ),
    ]
